sudo: required
services:
  - docker

before_install:
  - docker build -t sinu/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true sinu/react-test npm test

after_success:
  - docker build -t sinu/multi-client ./client
  - docker build -t sinu/multi-server ./server
  - docker build -t sinu/multi-nginx ./nginx
  - docker build -t sinu/multi-worker ./worker
# login to docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin


# push the images to docker hub
  - docker push sinu/multi-client
  - docker push sinu/multi-server
  - docker push sinu/multi-nginx
  - docker push sinu/multi-worker
#end of file

deploy:
  provider: elasticbeanstalk
  region: eu-west-2
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-eu-west-2-874303585166
  backet_path: docker-multi
  on:
    branch: master
  access_key_id:
    secure: $AWS_ACCESS_KEY
  secret_access_key: :
    secure: $AWS_SECRET_KEY
